# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
runs:
 using: 'docker'
 image: 'Dockerfile'

outputs:
 message:
    description: 'The message printed by the Docker container'
    value: ${{ steps.hello-world.outputs.message }}