on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hello-world-action ./hello-world-docker-action

      - name: Run Docker
        run: docker run hello-world-action
