on: [push]

jobs:
  puml_creator:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Render PlantUML files') == false && contains(github.event.head_commit.message, 'Create PlantUML files') == false
    name: Create PUML Files from XML
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker
        run: |
          docker compose up --build
          git config --global user.email "mattis.fieseler@wago.com"
          git config --global user.name "Mattis Fieseler"
          git add *
          git commit -m "Create PlantUML files"
          git push
