on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Render PlantUML files') == false && contains(github.event.head_commit.message, 'Create PlantUML files') == false
    name: A Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hello-world-action .

      - name: Run Docker
        run: |
          docker run --rm -v $(pwd):/app hello-world-action

      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
