on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Render PlantUML files') == false && contains(github.event.head_commit.message, 'Create PlantUML files') == false
    name: A Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hello-world-action .

      - name: Run Docker
        run: |
          docker run --rm -v $(pwd):/app hello-world-action
      - name: Upload file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: core
          path: ./docs/core.puml
  generate_plantuml:
    needs: hello_world_job
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Render PlantUML files') == false && contains(github.event.head_commit.message, 'Create PlantUML files') == false
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: core
        path: docs  # Directory to download the artifact to
    - name: listdir
      run: ls -R
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: docs
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      