on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hello-world-action .

      - name: Run Docker
        run: docker run --rm -v $(pwd):/app hello-world-action 
  generate_plantuml:
    needs: hello_world_job
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: .
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      